### ISSUE TITLE
Provide *only* third party icons

### ISSUE THREAD

**Issue by speltriao** [Bonandry/yaru-plus#48]
Ciao! Mi piace molto questo tema

Io volevo sapere se sarebbe possibile di fare una opzione per cambiare solamente gli icone che *non* ci sono in Yaru officiale, perché mi piacciono molto anche gli officiali. In questo modo, Yaru+ sarebbe un "complemento" di Yaru.

Grazie

**Comment by gusbemacbe** [comment]
Buonotte, @speltriao !

L'utente @btd1337 mi ha già suggerito ciò e anche ne detto. Lui mi ha fornito il suo script. Ne ho già detto al @Bonandry. 

Per favore, osserva che @Bonandry è appena un designer grafico e non un sviluppatore. Posso fare ciò con lo script del @btd1337. 

Ma a causa dell'epidemica di COVID-19 in Brasile, come la mia famiglia era asintomatica, io sospettavo che avessero COVID-19 molto leggero, io mi sono trasferito nella «camera da letto santuario» dal 28 marzo, per evitare il contatto con loro. Non posso stare in mia camera da letto fino all'11 maggio.

Sul santuario, ho un computer portatile con Windows 10, ma lui non è troppo buono para sviluppare le icone dei progetti di @Bonandry.

Per favore, scusami per la mia assenza!

**Comment by speltriao** [comment]
Buonasera! Ma che pazzo io, anche tu sei brasiliano; potremmo parlare anche in portoghese.
Lo so che qui COVID è veramente difficile, non è bisogno nessuna fretta. Windows è sempre cattivo per sviluppare (per me, almeno)  e io non so molto di bash scripts neanche de scripts per icons per aiutarvi. Ci volevo volentieri! 

Grazie per il poggetto, continuerò a cercare i bug nel futuro

**Comment by btd1337** [comment]
This is my script to use only third party icons:

https://github.com/btd1337/urutau-icons/blob/master/scripts/clean-install.sh

It generates symbolic links to original elementary icons.

Feel free to modify it according to your needs.

**Comment by gusbemacbe** [comment]
Hello @btd1337 

I need your little and quick help.

Canonical's Yaru size hierarchy is different from @Bonandry's Yaru++'s. Do I need to create the own Yaru++ Minimal based on Canonical's Yaru size hierarchy?

**Comment by gusbemacbe** [comment]
Uploading [UnixStackExchange.zip](https://github.com/Bonandry/yaru-plus/files/5013472/UnixStackExchange.zip)...

**Comment by gusbemacbe** [comment]
Ciao/hello @btd1337, @DarthWound and @speltriao!

<details>
  <summary>English (for @btd1337 and @DarthWound)</summary>
  
  I have just released Yaru++ Minimal, in spite of not so good results.

  You should test and try it at the branch <code>gusbemacbe</code>, but if you do not like it, unfortunately then Yaru++ Minimal is useless, because Yaru++ uses the format SVG and the original Yaru uses the format PNG. Original Yaru icons are not scalable, therefore, I used the maximium with @2x.

  @Bonandry does not approve this icons theme because of different formats. 

  I will release this new version this week.
</details>

<details>
  <summary>Italiano (per @speltriao)</summary>
  
  Ho appena rilasciato Yaru++ Minimo, nonostante i risultati non siano buoni.

  Tu devi provare e provarlo sulla <i>branch</i> <code> gusbemacbe</code>, ma se non ti piace, sfortunatamente Yaru++ Minimo è inutile, perché Yaru++ usa il formato SVG e Yaru originale usa il formato PNG. Le icone del Yaru originale non sono scalabili, perciò, ho usato il massimo con @2x.

  @Bonandry non approva questo tema di icone a causa dei differenti formati.

  Rilascerò questa nuova versione questa settimana.
</details>

**Comment by speltriao** [comment]
Ciao a tutti! 
Ho trovato un modo semplici per fare Yaru++ essere usato solamente per gli applicazioni di terzi "Third Party". Come root, ho modificato l'archivio /usr/share/icons/Yaru/index.theme .
Ho cambiato la linea:  Inherits= Humanity,hicolor  per  Inherits=Yaru++, Humanity,hicolor 

Ecco! Funziona.

**Comment by gusbemacbe** [comment]
@speltriao 

Grazie, vado notare il tuo hacl per il README.
