### ISSUE TITLE
It needs an upgrade.

### ISSUE THREAD

**Issue by laichiaheng** [Bonandry/yaru-plus#49]
There is new Yaru theme now.

**Comment by Bonandry** [comment]
we're working on it

**Comment by gusbemacbe** [comment]
Hi @laichiaheng !

Many new Yaru icons from Ubuntu developers came from Yaru++. I am one of its collaborators. 

Please observe that @Bonandry is just a graphic designer. He can not fix the bugs and merge the beta and unstable branches into the official branch, because it is danger, so he broke Adwaita++ and Yaru++. Only I can do it, as I am a developer, expert in git and system analyst. 

I asked @Bonandry to keep working on new icons. But as for me, I can not work with @Bonandry icons projects, because I am not at my bedroom with a super-computer with Linux, I am at the "sanctuary bedroom" with a laptop with Windows 10 and activated WSL since late March, so my family is asymptomatic and I suspected they had light COVID-19. I can return to my bedroom only on May 11. Windows 10 with activated WSL is not good for developing icons projects. 

Please, I am very sorry for my long absence. Thank you for your attention, patience and understanding!

**Comment by gusbemacbe** [comment]
Now I am working on the upgrade.
