### ISSUE TITLE
Typing error in index.theme : emmoltes/emotes

### ISSUE THREAD

**Issue by Amathadius** [Bonandry/yaru-plus#53]
You probably wanted to say `emotes/symbolic` instead of `emmoltes/symbolic` in the directory section of index.theme.

**Comment by gusbemacbe** [comment]
Hello/Salut @Amathadius 

🇬🇧 It has already been fixed some months ago, in other branches, in reference to https://github.com/Bonandry/yaru-plus/issues/39, we just did not upgrade from the beta branch to the official branch because of the coronavirus outbreak.
🇫🇷 Il a déjà résolu il y a quelque mois, in autres branches, en réferénce au to https://github.com/Bonandry/yaru-plus/issues/39, nous n'avons juste pas fait upgrade de la branch béta à la branch officielle à cause de la pandémie de coronavirus.

**Comment by gusbemacbe** [comment]
@Amathadius 

:gb: Please use the icons themes from the branch `gusbemacbe`. Soon it will be pushed to the branch `master`.
:fr: S'il vous plait, voudriez utiliser les thèmes d'icônes de la *branch* `gusbemacbe`. Bientôt, il sera envoyée vers la *branch* `master`.
